### ISSUE TITLE
bluetooth functionality

### ISSUE THREAD

**Issue by jappyjan** [FreeYourStream/freedeck-ino#23]
Would be cool to also use this via bluetooth and battery powered.

You could use a simple HC05 as Bluetooth HID Device (change firmware beforehands https://www.instructables.com/3-Bluetooth-HID-Module-HC05-With-RN42-Firmware/) and would only need small code changes.

I will/would look into this in the future as soon as i have time to order and assemble the parts needed to build my own freedeck. so for now i will only open this feature request and maybe someone else likes the idea and starts to work on it :)

**Comment by eabase** [comment]
Not sure this is possible without a lot of extra hacking since the BT stack is huge... but then again it depends on how large the other packages are.

**Comment by koriwi** [comment]
feel free to reopen.
Cleaning up the issues

**Comment by ryanaukes** [comment]
Hey @jappyjan,
Are you still planning to make this feature? It would be really usefull for me too.
