### ISSUE TITLE
Short press to change to another page, can execute a long press callback in the new page.

### ISSUE THREAD

**Issue by eipporko** [FreeYourStream/freedeck-ino#29]
PCB - 1.2
Firmware - 2.2.0

I just found that, if you press a button to change to another page, if is defined a long press action in the new one, this action also is executed.

I tried to increase in the settings the LONG_PRESS_DURATION parameter to an exagerated time like 10000ms, and doing this thing of change page, the freedeck executed the long press action although the 10 seconds was not reached.

I made a sketch to trying to explain myself
- I pressed the button in the page 4 to change to page 0 and executed the long press option in the page 0
![Captura de pantalla de 2021-10-01 10-03-59](https://user-images.githubusercontent.com/2479373/135588220-7ffa3c96-3468-4f19-8cdc-b8c219d2b17c.png)

**Comment by koriwi** [comment]
Hey. Thanks for the explanation and details. i already fixed this issue in the pi pico firmware. tried to do the same for this and failed :sweat_smile: 
it buggs me so i will try to do it ASAP

**Comment by koriwi** [comment]
Fixed in develop
