### ISSUE TITLE
IDEA: Secondary Action on Buttons (A Secondary Action AFTER completing primary action, *NOT* the same as Short Press or Long Hold Function)

### ISSUE THREAD

**Issue by IAmOrion** [FreeYourStream/freedeck-ino#34]
A Secondary Action AFTER completing primary action, **NOT** the same as Short Press or Long Hold Function.

Can we add a simple secondary action to each "trigger" that can be configured via the configurator such as toggle switch for each button and action (So the toggle can be different on Short Press and Long Press is required) that says something like "Return to page x after action" 

So in other words, once the Short Press (in my case set as Hot Key) has been triggered it then automatically goes back to the start page or a page of choice.

Think like Windows Start Menu -- You press windows key or menu, the windows menu opens, you then click your app to open it, and the windows menu closes itself.  This is the action I mean.  So that upon pressing button, it completes the chose command such as pressing a hot key combo (which is set up to launch an app) and then it goes back to start page as a secondary action.

Not to be confused with a secondary action on the button itself > I'm not referring to Short Press as Primary and Long Press as Secondary.  I'm talking about an actual secondary action on both of those triggers

I will copy this idea over to the freedeck code github too, since technically they're tied together as the function needs to be in the configurator for the code to work with

**Comment by koriwi** [comment]
live on develop branch
